/**
 * main.c — ARM Cortex-A9 Firmware for MLP Accelerator
 * ====================================================
 *
 * This firmware runs on the Zynq Processing System (PS) and controls
 * the MLP accelerator implemented in the Programmable Logic (PL).
 *
 * Communication: AXI GPIO
 *   - axi_gpio_ctrl (PS→PL):  start bit, pixel data
 *   - axi_gpio_status (PL→PS): done flag, predicted class
 *
 * Flow:
 *   1. Load test image from DDR memory
 *   2. Send pixels one by one to the PL accelerator
 *   3. Assert start signal
 *   4. Wait for done signal
 *   5. Read predicted class from status GPIO
 *   6. Print result via UART
 *   7. Repeat for all test images
 *
 * Build: Vitis Unified IDE (2023.1+)
 * Board: Zybo Z7-20 (Zynq-7020)
 *
 * Hardware dependencies:
 *   - Block design with axi_gpio_ctrl and axi_gpio_status
 *   - Addresses defined in xparameters.h (generated by Vivado)
 */

#include <stdio.h>
#include <xil_printf.h>
#include "xparameters.h"
#include "xgpio.h"
#include "xil_exception.h"
#include "xscugic.h"
#include "xil_cache.h"
#include "sleep.h"

//=============================================================================
// Hardware Configuration (match Vivado block design)
//=============================================================================
#define GPIO_CTRL_DEVICE_ID     XPAR_AXI_GPIO_CTRL_DEVICE_ID
#define GPIO_STATUS_DEVICE_ID   XPAR_AXI_GPIO_STATUS_DEVICE_ID
#define INTC_DEVICE_ID          XPAR_SCUGIC_SINGLE_DEVICE_ID

#define GPIO_CTRL_CHANNEL1      1   // start/rst bits
#define GPIO_CTRL_CHANNEL2      2   // pixel data
#define GPIO_STATUS_CHANNEL1    1   // done + predicted

// Bit assignments within GPIO channels
#define START_BIT               0
#define RST_BIT                 1
#define DONE_BIT                0
#define PREDICTED_SHIFT         4
#define PREDICTED_MASK          0x0F

// MLP parameters
#define IMG_SIZE                784
#define NUM_TEST_IMAGES         10
#define CLK_PERIOD_NS           10      // 100 MHz

//=============================================================================
// Global Variables
//=============================================================================
XGpio gpio_ctrl;
XGpio gpio_status;

// Test images: 10 MNIST digits (generated by quantize_export.py)
// Format: Q8.8 signed fixed-point (16-bit)
// Imported from co-processed header file
#include "test_images.h"

//=============================================================================
// Function Prototypes
//=============================================================================
int  init_peripherals(void);
void send_image_to_pl(short *image_q88);
void start_inference(void);
int  wait_for_done(void);
int  get_prediction(void);
int  run_single_inference(short *image_q88);
void print_banner(void);
void print_result(int img_idx, int predicted, int expected);
void print_summary(int pass, int fail, int total);

//=============================================================================
// Initialization
//=============================================================================
int init_peripherals(void)
{
    int status;

    // Initialize GPIO controllers
    status = XGpio_Initialize(&gpio_ctrl, GPIO_CTRL_DEVICE_ID);
    if (status != XST_SUCCESS) {
        xil_printf("ERROR: Failed to initialize GPIO CTRL (0x%x)\r\n",
                   XPAR_AXI_GPIO_CTRL_BASEADDR);
        return XST_FAILURE;
    }

    status = XGpio_Initialize(&gpio_status, GPIO_STATUS_DEVICE_ID);
    if (status != XST_SUCCESS) {
        xil_printf("ERROR: Failed to initialize GPIO STATUS (0x%x)\r\n",
                   XPAR_AXI_GPIO_STATUS_BASEADDR);
        return XST_FAILURE;
    }

    // Set data directions
    // Channel 1: all outputs (start, rst)
    XGpio_SetDataDirection(&gpio_ctrl, GPIO_CTRL_CHANNEL1, 0x00000000);
    // Channel 2: all outputs (pixel data)
    XGpio_SetDataDirection(&gpio_ctrl, GPIO_CTRL_CHANNEL2, 0x00000000);
    // Channel 1: all inputs (done, predicted)
    XGpio_SetDataDirection(&gpio_status, GPIO_STATUS_CHANNEL1, 0x000000FF);

    // Set default values
    XGpio_DiscreteWrite(&gpio_ctrl, GPIO_CTRL_CHANNEL1, 0x00000000);
    XGpio_DiscreteWrite(&gpio_ctrl, GPIO_CTRL_CHANNEL2, 0x00000000);

    xil_printf("  [OK] GPIO initialized\r\n");
    xil_printf("       CTRL  base: 0x%08x\r\n", XPAR_AXI_GPIO_CTRL_BASEADDR);
    xil_printf("       STATUS base: 0x%08x\r\n", XPAR_AXI_GPIO_STATUS_BASEADDR);

    return XST_SUCCESS;
}

//=============================================================================
// MLP Accelerator Control Functions
//=============================================================================

/**
 * Send 784 pixels to the PL accelerator via GPIO.
 * Each pixel is a 16-bit Q8.8 fixed-point value.
 */
void send_image_to_pl(short *image_q88)
{
    for (int i = 0; i < IMG_SIZE; i++) {
        // Write pixel to GPIO channel 2
        XGpio_DiscreteWrite(&gpio_ctrl, GPIO_CTRL_CHANNEL2,
                            (u32)(image_q88[i] & 0xFFFF));

        // Small delay to let the PL capture the data
        // (approximately 1-2 clock cycles at 100 MHz ≈ 10-20 ns)
        // In practice, the PL uses the pixel_valid signal timing.
        // For GPIO-based transfer, a short nop delay suffices.
        usleep(1);  // 1 microsecond per pixel ≈ 784 µs total
    }
}

/**
 * Assert the start signal to begin inference.
 * Requires a pulse: 1 → 0.
 */
void start_inference(void)
{
    // Assert start
    XGpio_DiscreteWrite(&gpio_ctrl, GPIO_CTRL_CHANNEL1,
                        1 << START_BIT);
    usleep(1);      // hold for ~1 µs

    // De-assert start
    XGpio_DiscreteWrite(&gpio_ctrl, GPIO_CTRL_CHANNEL1, 0);
}

/**
 * Wait for the PL to assert the done signal.
 * Returns the number of microseconds waited.
 */
int wait_for_done(void)
{
    u32 status;
    int elapsed_us = 0;

    // Poll the status GPIO until done is asserted
    do {
        status = XGpio_DiscreteRead(&gpio_status, GPIO_STATUS_CHANNEL1);
        usleep(10);  // poll every 10 µs
        elapsed_us += 10;

        // Safety timeout: 10 ms (should never happen)
        if (elapsed_us > 10000) {
            xil_printf("WARNING: Inference timeout!\r\n");
            return -1;
        }
    } while (!(status & (1 << DONE_BIT)));

    return elapsed_us;
}

/**
 * Read the predicted class from the status GPIO.
 * Bits 4-7 contain the 4-bit predicted label.
 */
int get_prediction(void)
{
    u32 status = XGpio_DiscreteRead(&gpio_status, GPIO_STATUS_CHANNEL1);
    return (status >> PREDICTED_SHIFT) & PREDICTED_MASK;
}

/**
 * Complete inference pipeline for a single image.
 * Returns the predicted label.
 */
int run_single_inference(short *image_q88)
{
    // Step 1: Send pixel data
    send_image_to_pl(image_q88);

    // Step 2: Start inference
    start_inference();

    // Step 3: Wait for completion
    int elapsed = wait_for_done();
    if (elapsed < 0) {
        return -1;  // timeout
    }

    // Step 4: Get result
    return get_prediction();
}

//=============================================================================
// Reporting Functions
//=============================================================================
void print_banner(void)
{
    xil_printf("\r\n");
    xil_printf("============================================\r\n");
    xil_printf("  MLP Neural Network Accelerator\r\n");
    xil_printf("  Zybo Zynq-7020  |  784→64→32→10  |  Q8.8\r\n");
    xil_printf("============================================\r\n");
    xil_printf("  System Clock:   100 MHz\r\n");
    xil_printf("  Pixel Transfer: %d µs/image\r\n", IMG_SIZE * 1);
    xil_printf("--------------------------------------------\r\n\n");
}

void print_result(int img_idx, int predicted, int expected)
{
    const char *status_str = (predicted == expected) ? "PASS" : "FAIL";

    xil_printf("  [%s] Image %2d: predicted=%d  expected=%d",
               status_str, img_idx, predicted, expected);

    if (predicted == expected) {
        xil_printf("\r\n");
    } else {
        xil_printf("  <-- MISMATCH\r\n");
    }
}

void print_summary(int pass, int fail, int total)
{
    float rate = 100.0f * pass / total;

    xil_printf("\r\n--------------------------------------------\r\n");
    xil_printf("  RESULTS: %d/%d passed (%.1f%%)\r\n",
               pass, total, rate);
    xil_printf("  FAILURES: %d\r\n", fail);
    xil_printf("--------------------------------------------\r\n");

    if (fail == 0) {
        xil_printf("  ★★★ ALL TESTS PASSED ★★★\r\n");
    } else {
        xil_printf("  ★★★ SOME TESTS FAILED ★★★\r\n");
    }
    xil_printf("============================================\r\n\n");
}

//=============================================================================
// Main
//=============================================================================
int main(void)
{
    int status;
    int predicted;
    int pass_count = 0;
    int fail_count = 0;

    // Disable data cache for GPIO region to avoid coherency issues
    Xil_DCacheDisable();

    // Print banner
    print_banner();

    // Initialize peripherals
    xil_printf("[INIT] Initializing peripherals...\r\n");
    status = init_peripherals();
    if (status != XST_SUCCESS) {
        xil_printf("FATAL: Peripheral initialization failed.\r\n");
        return XST_FAILURE;
    }

    // Run inference on each test image
    xil_printf("\r\n[RUN] Running %d inference tests...\r\n\n",
               NUM_TEST_IMAGES);

    for (int img = 0; img < NUM_TEST_IMAGES; img++) {
        predicted = run_single_inference(test_images[img]);

        if (predicted < 0) {
            xil_printf("  [SKIP] Image %2d: inference timeout\r\n", img);
            fail_count++;
            continue;
        }

        print_result(img, predicted, test_labels[img]);

        if (predicted == test_labels[img]) {
            pass_count++;
        } else {
            fail_count++;
        }
    }

    // Print summary
    print_summary(pass_count, fail_count, NUM_TEST_IMAGES);

    return (fail_count == 0) ? XST_SUCCESS : XST_FAILURE;
}
